FROM public.ecr.aws/lambda/python:3.10

COPY requirements.txt .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY *.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "create_index.handler" ]

# Set cache to a location lambda can write to
ENV TRANSFORMERS_CACHE="/tmp/TRANSFORMERS_CACHE"

